export const IOS_SIZE_MAP = [
  { size: 20, scale: "2x", idiom: "iphone", filename: "40.png" },
  { size: 20, scale: "3x", idiom: "iphone", filename: "60.png" },
  { size: 29, scale: "1x", idiom: "iphone", filename: "29.png" },
  { size: 29, scale: "2x", idiom: "iphone", filename: "58.png" },
  { size: 29, scale: "3x", idiom: "iphone", filename: "87.png" },
  { size: 40, scale: "2x", idiom: "iphone", filename: "80.png" },
  { size: 40, scale: "3x", idiom: "iphone", filename: "120.png" },
  { size: 57, scale: "1x", idiom: "iphone", filename: "57.png" },
  { size: 57, scale: "2x", idiom: "iphone", filename: "114.png" },
  { size: 60, scale: "2x", idiom: "iphone", filename: "120.png" },
  { size: 60, scale: "3x", idiom: "iphone", filename: "180.png" },

  { size: 20, scale: "1x", idiom: "ipad", filename: "20.png" },
  { size: 20, scale: "2x", idiom: "ipad", filename: "40.png" },
  { size: 29, scale: "1x", idiom: "ipad", filename: "29.png" },
  { size: 29, scale: "2x", idiom: "ipad", filename: "58.png" },
  { size: 40, scale: "1x", idiom: "ipad", filename: "40.png" },
  { size: 40, scale: "2x", idiom: "ipad", filename: "80.png" },
  { size: 50, scale: "1x", idiom: "ipad", filename: "50.png" },
  { size: 50, scale: "2x", idiom: "ipad", filename: "100.png" },
  { size: 72, scale: "1x", idiom: "ipad", filename: "72.png" },
  { size: 72, scale: "2x", idiom: "ipad", filename: "144.png" },
  { size: 76, scale: "1x", idiom: "ipad", filename: "76.png" },
  { size: 76, scale: "2x", idiom: "ipad", filename: "152.png" },
  { size: 83.5, scale: "2x", idiom: "ipad", filename: "167.png" },

  { size: 1024, scale: "1x", idiom: "ios-marketing", filename: "1024.png" },

  { size: 16, scale: "1x", idiom: "mac", filename: "16.png" },
  { size: 16, scale: "2x", idiom: "mac", filename: "32.png" },
  { size: 32, scale: "1x", idiom: "mac", filename: "32.png" },
  { size: 32, scale: "2x", idiom: "mac", filename: "64.png" },
  { size: 128, scale: "1x", idiom: "mac", filename: "128.png" },
  { size: 128, scale: "2x", idiom: "mac", filename: "256.png" },
  { size: 256, scale: "1x", idiom: "mac", filename: "256.png" },
  { size: 256, scale: "2x", idiom: "mac", filename: "512.png" },
  { size: 512, scale: "1x", idiom: "mac", filename: "512.png" },
  { size: 512, scale: "2x", idiom: "mac", filename: "1024.png" },

  {
    size: 24,
    scale: "2x",
    idiom: "watch",
    role: "notificationCenter",
    subtype: "38mm",
    filename: "48.png",
  },
  {
    size: 27.5,
    scale: "2x",
    idiom: "watch",
    role: "notificationCenter",
    subtype: "42mm",
    filename: "55.png",
  },
  {
    size: 29,
    scale: "2x",
    idiom: "watch",
    role: "companionSettings",
    filename: "58.png",
  },
  {
    size: 29,
    scale: "3x",
    idiom: "watch",
    role: "companionSettings",
    filename: "87.png",
  },
  {
    size: 33,
    scale: "2x",
    idiom: "watch",
    role: "notificationCenter",
    subtype: "45mm",
    filename: "66.png",
  },
  {
    size: 40,
    scale: "2x",
    idiom: "watch",
    role: "appLauncher",
    subtype: "38mm",
    filename: "80.png",
  },
  {
    size: 44,
    scale: "2x",
    idiom: "watch",
    role: "appLauncher",
    subtype: "40mm",
    filename: "88.png",
  },
  {
    size: 46,
    scale: "2x",
    idiom: "watch",
    role: "appLauncher",
    subtype: "41mm",
    filename: "92.png",
  },
  {
    size: 50,
    scale: "2x",
    idiom: "watch",
    role: "appLauncher",
    subtype: "44mm",
    filename: "100.png",
  },
  {
    size: 86,
    scale: "2x",
    idiom: "watch",
    role: "quickLook",
    subtype: "38mm",
    filename: "172.png",
  },
  {
    size: 98,
    scale: "2x",
    idiom: "watch",
    role: "quickLook",
    subtype: "42mm",
    filename: "196.png",
  },
  {
    size: 108,
    scale: "2x",
    idiom: "watch",
    role: "quickLook",
    subtype: "44mm",
    filename: "216.png",
  },
  { size: 1024, scale: "1x", idiom: "watch-marketing", filename: "1024.png" },
];
