name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version_choice:
        description: "Which type of version bump? (patch, minor, major)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Bump version
        id: bump_version
        run: |
          npm version ${{ github.event.inputs.version_choice }}
          echo "::set-output name=new_version::$(node -p -e "require('./package.json').version")"

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes to GitHub
        run: |
          git push origin HEAD:master --follow-tags
